# Use the official Node.js image as the base image
FROM node:20

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Copy the rest of the application code
COPY . .

ARG JWT_SECRET
ENV JWT_SECRET=$JWT_SECRET

ARG NEXTAUTH_URL
ENV NEXTAUTH_URL=$NEXTAUTH_URL

ARG AUTH_SECRET
ENV AUTH_SECRET=$AUTH_SECRET

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

ARG SOLANA_ENDPOINT
ENV SOLANA_ENDPOINT=$SOLANA_ENDPOINT

ARG GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID

ARG GOOGLE_CLIENT_SECRET
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET

ARG GMAIL_USER
ENV GMAIL_USER=$GMAIL_USER

ARG GMAIL_PASSWORD
ENV GMAIL_PASSWORD=$GMAIL_PASSWORD

ARG RECLAIM_CALLBACK_URL
ENV RECLAIM_CALLBACK_URL=$RECLAIM_CALLBACK_URL

ARG RECLAIM_APP_SECRET
ENV RECLAIM_APP_SECRET=$RECLAIM_APP_SECRET

# Install dependencies
RUN npm install

# Build the Next.js application
RUN npm run build --force

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
